package com.msa.app.controllers;

import com.msa.app.dtos.UserDTO;
import com.msa.app.entities.User;
import com.msa.app.services.UserService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController// This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
@CrossOrigin("http://localhost:4200")
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    // POST
    // TODO: https://www.baeldung.com/spring-response-entity
    @PostMapping(path="/saveUser") // Map ONLY POST Requests
    public ResponseEntity<User> addNewUser(@RequestBody UserDTO userDTO) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return new ResponseEntity<User>(userService.addUser(userDTO), HttpStatus.OK);
    }

    // GET
    @GetMapping(path = "/showAllUsers")
    public ResponseEntity<List<User>> getUsers(){
        return new ResponseEntity<List<User>>(userService.getAllUsers(), HttpStatus.OK);
    }


    // DELETE
    @DeleteMapping(path = "/removeUserById/{id}") // path variable
    public void removeUser(@PathVariable Integer id){
        userService.deleteUser(id);
    }


    // PUT
    @PutMapping(path="/editUserById/{id}")
    public ResponseEntity<User> editUser(@RequestBody UserDTO userDTO, @PathVariable("id") Integer id) {
        Optional<User> searchedUser = userService.editUser(userDTO, id);
        if (searchedUser.isPresent())
            return new ResponseEntity<User>(searchedUser.get(), HttpStatus.OK);

        return new ResponseEntity<User>(HttpStatus.NOT_FOUND);
    }
}