package com.msa.app.controllers;

import com.msa.app.dtos.UserDTO;
import com.msa.app.entities.User;
import com.msa.app.services.UserService;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    @PostMapping(path="/saveUser") // Map ONLY POST Requests
    public User addNewUser(@RequestBody UserDTO userDTO) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return userService.addUser(userDTO);
    }

    @GetMapping(path = "/showAllUsers")
    public List<User> getUsers(){
        return userService.getAllUsers();
    }

    @DeleteMapping(path = "/removeUserById/{id}") // path variable
    public void removeUser(@PathVariable Integer id){
        userService.deleteUser(id);
    }

    @PutMapping(path="/editUserById/{id}")
    public User editUser(@RequestBody UserDTO userDTO, @PathVariable("id") Integer id) {
        return userService.editUser(userDTO, id);
    }
}